/**
 * Report Preview Component
 * Preview modal for reports before download
 */

'use client';

import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Download, FileText, FileSpreadsheet } from 'lucide-react';
import type { ReportListItem } from '@/stores/reports-store';

interface ReportPreviewProps {
  report: ReportListItem;
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onDownload: () => void;
}

function formatFileSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(2)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
}

function formatDate(dateString: string): string {
  const date = new Date(dateString);
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

function isExpired(expiresAt: string): boolean {
  return new Date(expiresAt) < new Date();
}

export function ReportPreview({ report, open, onOpenChange, onDownload }: ReportPreviewProps) {
  const expired = isExpired(report.expiresAt);

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            {report.format === 'PDF' ? (
              <FileText className="h-5 w-5 text-red-400" />
            ) : (
              <FileSpreadsheet className="h-5 w-5 text-green-400" />
            )}
            Report Preview
          </DialogTitle>
          <DialogDescription>
            Report details and download information
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4">
          {/* Report Name */}
          <div>
            <label className="text-sm font-medium text-muted-foreground">File Name</label>
            <p className="mt-1 text-sm">{report.fileName}</p>
          </div>

          {/* Version */}
          <div>
            <label className="text-sm font-medium text-muted-foreground">Version</label>
            <p className="mt-1 text-sm">{report.version?.name || 'N/A'}</p>
          </div>

          {/* Type and Format */}
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="text-sm font-medium text-muted-foreground">Report Type</label>
              <div className="mt-1">
                <Badge variant="outline">
                  {report.reportType.replace('_', ' ')}
                </Badge>
              </div>
            </div>
            <div>
              <label className="text-sm font-medium text-muted-foreground">Format</label>
              <div className="mt-1">
                <Badge variant="outline">{report.format}</Badge>
              </div>
            </div>
          </div>

          {/* File Size and Generation Date */}
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="text-sm font-medium text-muted-foreground">File Size</label>
              <p className="mt-1 text-sm">{formatFileSize(report.fileSize)}</p>
            </div>
            <div>
              <label className="text-sm font-medium text-muted-foreground">Generated</label>
              <p className="mt-1 text-sm">{formatDate(report.generatedAt)}</p>
            </div>
          </div>

          {/* Expiration */}
          <div>
            <label className="text-sm font-medium text-muted-foreground">Expires</label>
            <div className="mt-1">
              {expired ? (
                <Badge variant="destructive">Expired</Badge>
              ) : (
                <Badge variant="default">Expires {formatDate(report.expiresAt)}</Badge>
              )}
            </div>
          </div>

          {/* Generated By */}
          <div>
            <label className="text-sm font-medium text-muted-foreground">Generated By</label>
            <p className="mt-1 text-sm">{report.generator.name || report.generator.email}</p>
          </div>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)}>
            Close
          </Button>
          <Button onClick={onDownload} disabled={expired}>
            <Download className="mr-2 h-4 w-4" />
            Download
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

